**Concatenation**

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [3]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [4]:
z = np.array([7,8,9])

In [5]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [7]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Splitting**

In [9]:
x = np.array([1,2,3,99,99,3,2,1])

In [10]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [11]:
a,b,c = np.split(x, [3,5])

In [12]:
a

array([1, 2, 3])

In [13]:
b

array([99, 99])

In [14]:
c

array([3, 2, 1])

In [15]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [17]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [19]:
right, left = np.hsplit(m, [2])

In [20]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Sorting**

In [22]:
v = np.array([2,1,4,3,5])

In [23]:
v

array([2, 1, 4, 3, 5])

In [24]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [25]:
v.sort()

In [26]:
v

array([1, 2, 3, 4, 5])

In [27]:
m = np.random.normal(20,5, (3,3))

In [28]:
m

array([[21.13055976, 20.70322942, 23.50336328],
       [14.47806415, 25.8583888 , 26.16016909],
       [23.66673206, 18.23898909, 13.8026754 ]])

In [29]:
np.sort(m, axis = 1)

array([[20.70322942, 21.13055976, 23.50336328],
       [14.47806415, 25.8583888 , 26.16016909],
       [13.8026754 , 18.23898909, 23.66673206]])

In [30]:
np.sort(m, axis = 0)

array([[14.47806415, 18.23898909, 13.8026754 ],
       [21.13055976, 20.70322942, 23.50336328],
       [23.66673206, 25.8583888 , 26.16016909]])