In [1]:
import numpy as np

In [2]:
a = np.random.randint(10, size = 10)
a

array([0, 4, 1, 6, 1, 1, 3, 2, 0, 5])

In [3]:
a[0]

0

In [4]:
a[-1]

5

In [5]:
a[0] = 100
a

array([100,   4,   1,   6,   1,   1,   3,   2,   0,   5])

In [6]:
m = np.random.randint(10, size = (3,5))
m

array([[3, 3, 8, 7, 6],
       [0, 4, 6, 3, 5],
       [3, 5, 7, 3, 6]])

In [7]:
m[0,0]

3

In [8]:
m[1, 4]

5

In [9]:
m[1, 4] = 99

In [10]:
m

array([[ 3,  3,  8,  7,  6],
       [ 0,  4,  6,  3, 99],
       [ 3,  5,  7,  3,  6]])

In [11]:
m[1,4] = 2.2

In [12]:
m

array([[3, 3, 8, 7, 6],
       [0, 4, 6, 3, 2],
       [3, 5, 7, 3, 6]])

In [13]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
a[0:3]

array([20, 21, 22])

In [16]:
a[:3]

array([20, 21, 22])

In [17]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [18]:
a[1::2]

array([21, 23, 25, 27, 29])

In [19]:
a[0::2]

array([20, 22, 24, 26, 28])

In [20]:
a[0::3]

array([20, 23, 26, 29])

In [21]:
a[::3]

array([20, 23, 26, 29])

In [22]:
m = np.random.randint(10, size = (5,5))

In [23]:
m

array([[9, 7, 9, 1, 7],
       [3, 9, 1, 0, 5],
       [5, 2, 9, 8, 2],
       [0, 0, 1, 9, 2],
       [0, 8, 5, 9, 1]])

In [24]:
m[:,0]

array([9, 3, 5, 0, 0])

In [25]:
m[:,1]

array([7, 9, 2, 0, 8])

In [26]:
m[:,4]

array([7, 5, 2, 2, 1])

In [27]:
m[0,:]

array([9, 7, 9, 1, 7])

In [28]:
m[0]

array([9, 7, 9, 1, 7])

In [29]:
m[0:2, 0:3]

array([[9, 7, 9],
       [3, 9, 1]])

In [30]:
m[:,0:2]

array([[9, 7],
       [3, 9],
       [5, 2],
       [0, 0],
       [0, 8]])

In [31]:
m[1:3, 0:2]

array([[3, 9],
       [5, 2]])

In [32]:
a = np.random.randint(10, size = (5, 5))
a

array([[3, 5, 0, 3, 2],
       [2, 6, 7, 5, 3],
       [1, 9, 6, 5, 8],
       [8, 4, 8, 0, 9],
       [0, 6, 5, 5, 2]])

In [33]:
alt_a = a[0:3, 0:2]
alt_a

array([[3, 5],
       [2, 6],
       [1, 9]])

In [34]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [35]:
alt_a

array([[99999,     5],
       [    2,   888],
       [    1,     9]])

In [36]:
a

array([[99999,     5,     0,     3,     2],
       [    2,   888,     7,     5,     3],
       [    1,     9,     6,     5,     8],
       [    8,     4,     8,     0,     9],
       [    0,     6,     5,     5,     2]])

In [37]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[9, 7],
       [3, 9],
       [5, 2]])

In [38]:
alt_b[0,0] = 9999

In [39]:
alt_b

array([[9999,    7],
       [   3,    9],
       [   5,    2]])

In [40]:
m

array([[9, 7, 9, 1, 7],
       [3, 9, 1, 0, 5],
       [5, 2, 9, 8, 2],
       [0, 0, 1, 9, 2],
       [0, 8, 5, 9, 1]])

**__Fancy Index__**

In [41]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [42]:
fetch=[1,3,5]

In [44]:
v[fetch]

array([ 3,  9, 15])

In [45]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [46]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [48]:
m[satir, sutun]

array([1, 5])

In [49]:
m[0, [1,2]]

array([1, 2])

In [50]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [51]:
v = np.array([1, 2, 3, 4, 5])

In [52]:
v < 3

array([ True,  True, False, False, False])

In [53]:
v[v < 3]

array([1, 2])

In [54]:
v[v > 3]

array([4, 5])

In [55]:
v[v >= 3]

array([3, 4, 5])

In [56]:
v[v == 3]

array([3])

In [57]:
v[v != 3]

array([1, 2, 4, 5])

In [58]:
v * 2

array([ 2,  4,  6,  8, 10])

In [59]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [60]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [61]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [62]:
v - 1

array([0, 1, 2, 3, 4])

In [63]:
v * 5

array([ 5, 10, 15, 20, 25])

In [64]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [65]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [66]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [67]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [68]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [69]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [70]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [71]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [72]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [73]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [74]:
np.absolute(np.array([-3]))

array([3])

In [75]:
np.sin(360)

0.9589157234143065

In [76]:
v = np.array([1,2,3])

In [77]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [78]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [79]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the buil

In [80]:
np.mean(v)

2.0

In [81]:
v.sum()

6

In [82]:
v.min()

1

In [83]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [84]:
a

array([[5, 1],
       [1, 3]])

In [85]:
b

array([12, 10])

In [86]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])