In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [4]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [5]:
a * b

array([ 2,  6, 12, 20])

In [6]:
type(a)

numpy.ndarray

In [7]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [8]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [11]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(10, 4, (3,4))

array([[ 7.13704672,  7.3958294 ,  9.53141765, 12.04251943],
       [ 5.18431362,  8.26308769, 10.10113906, 13.19447537],
       [12.81312987, 11.82252219,  8.96326144,  6.40235522]])

In [14]:
np.random.randint(0,10, (3,3))

array([[4, 1, 9],
       [2, 3, 3],
       [0, 2, 2]])

In [15]:
np.random.randint(10, size = 10)

array([4, 2, 8, 6, 9, 8, 4, 8, 2, 6])

In [16]:
a = np.random.randint(10, size = 10)

In [17]:
a.ndim

1

In [18]:
a.shape

(10,)

In [19]:
a.size

10

In [20]:
a.dtype

dtype('int32')

In [21]:
b = np.random.randint(10, size = (3,5))
b

array([[5, 1, 8, 3, 4],
       [6, 0, 4, 4, 7],
       [3, 4, 3, 5, 2]])

In [22]:
b.ndim

2

In [23]:
b.shape

(3, 5)

In [24]:
b.size

15

In [25]:
b.dtype

dtype('int32')

**Reshaping**

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a = np.arange(1,10)

In [29]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a.ndim

1

In [31]:
b = a.reshape((1,9))

In [32]:
b.ndim

2