In [1]:
import numpy as np

In [2]:
population = np.random.randint(0,80,10000)

In [3]:
population[0:10]

array([70, 46, 78, 38, 78, 33, 66, 34, 35, 60])

In [4]:
np.random.seed(115)
sample = np.random.choice(a=population,size=100)
sample[0:10]

array([59, 17, 49, 49, 51, 20, 65, 13, 20, 21])

In [5]:
sample.mean()

35.45

In [6]:
population.mean()

39.6128

In [7]:
np.random.seed(10)
sample1 = np.random.choice(a = population, size = 100)
sample2 = np.random.choice(a = population, size = 100)
sample3 = np.random.choice(a = population, size = 100)
sample4 = np.random.choice(a = population, size = 100)
sample5 = np.random.choice(a = population, size = 100)
sample6 = np.random.choice(a = population, size = 100)
sample7 = np.random.choice(a = population, size = 100)
sample8 = np.random.choice(a = population, size = 100)
sample9 = np.random.choice(a = population, size = 100)
sample10 = np.random.choice(a = population, size = 100)

In [8]:
(sample1.mean() + sample2.mean() + sample3.mean() + sample4.mean() + sample5.mean() 
+ sample6.mean() + sample7.mean() + sample8.mean() + sample9.mean() + sample10.mean() )  / 10

39.379000000000005

In [9]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [10]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [11]:
!pip install researchpy
import researchpy as rp

In [12]:
rp.summary_cont(df[["total_bill","tip","size"]])

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [13]:
rp.summary_cat(df[["sex","smoker","day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [14]:
df[["tip","total_bill"]].cov()

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [15]:
df[["tip","total_bill"]].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

# **_Example_**

In [16]:
import numpy as np
price = np.random.randint(10,110, 1000)

In [17]:
price.mean()

58.492

In [18]:
import statsmodels.stats.api as sms

In [22]:
sms.DescrStatsW(price).tconfint_mean()

(56.67953887736034, 60.30446112263965)

# Bernoulli

${\displaystyle f(k;p)=p^{k}(1-p)^{1-k}\quad {\text{for }}k\in \{0,1\}}$


${\displaystyle \operatorname {E} \left(X\right)=p}$

$\operatorname {Var} [X]=pq=p(1-p)$

In [23]:
from scipy.stats import bernoulli

In [24]:
p = 0.6

In [25]:
rv = bernoulli(p)
rv.pmf(k = 0)

0.4

# Law of large numbers

NameError: name 'rng' is not defined

In [27]:
import numpy as np
rng = np.random.RandomState(123)
for i in np.arange(1,21):
    deney_sayisi = 2**i
    yazi_turalar = rng.randint(0, 2, size = deney_sayisi)
    yazi_olasiliklari = np.mean(yazi_turalar)
    print("Atış Sayısı:",deney_sayisi,"---",'Yazı Olasılığı: %.2f' % (yazi_olasiliklari * 100))

Atış Sayısı: 2 --- Yazı Olasılığı: 50.00
Atış Sayısı: 4 --- Yazı Olasılığı: 0.00
Atış Sayısı: 8 --- Yazı Olasılığı: 62.50
Atış Sayısı: 16 --- Yazı Olasılığı: 43.75
Atış Sayısı: 32 --- Yazı Olasılığı: 46.88
Atış Sayısı: 64 --- Yazı Olasılığı: 56.25
Atış Sayısı: 128 --- Yazı Olasılığı: 50.78
Atış Sayısı: 256 --- Yazı Olasılığı: 52.73
Atış Sayısı: 512 --- Yazı Olasılığı: 52.93
Atış Sayısı: 1024 --- Yazı Olasılığı: 50.20
Atış Sayısı: 2048 --- Yazı Olasılığı: 48.58
Atış Sayısı: 4096 --- Yazı Olasılığı: 49.49
Atış Sayısı: 8192 --- Yazı Olasılığı: 49.58
Atış Sayısı: 16384 --- Yazı Olasılığı: 49.96
Atış Sayısı: 32768 --- Yazı Olasılığı: 50.00
Atış Sayısı: 65536 --- Yazı Olasılığı: 49.68
Atış Sayısı: 131072 --- Yazı Olasılığı: 49.97
Atış Sayısı: 262144 --- Yazı Olasılığı: 50.13
Atış Sayısı: 524288 --- Yazı Olasılığı: 50.01
Atış Sayısı: 1048576 --- Yazı Olasılığı: 50.09


In [28]:
rng.randint(0, 2, size = 5)

array([1, 1, 1, 1, 0])