In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[1:5]

array([2, 3, 4, 5])

In [4]:
arr[:4]

array([1, 2, 3, 4])

In [5]:
arr[::2]

array([1, 3, 5, 7, 9])

In [6]:
arrCopy = arr.copy()
arrCopy[:3] = 25
arrCopy

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
newArray = np.arange(1,21)
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
newArray = newArray.reshape(4,5)
newArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [11]:
newArray[:,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [12]:
newArray[:2,:2]

array([[1, 2],
       [6, 7]])

In [13]:
newArray[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [16]:
boolValuesArray = arr > 3
boolValuesArray

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [17]:
arr[boolValuesArray]

array([4, 5, 6, 7, 8, 9])

In [18]:
arr[arr > 5]

array([6, 7, 8, 9])