In [1]:
data_list = [1,2,3,4]

In [2]:
data_list

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
arr = np.array(data_list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
data_list2 = [[10,20,30],[40,50,60],[70,80,90]]

arr2 = np.array(data_list2)

arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr2[2,2]

90

In [7]:
arr3 = np.array([1,2,3])
arr3

array([1, 2, 3])

In [8]:
arr[0]

1

In [9]:
arr[2]

3

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [20]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.random.randint(0,10)

3

In [23]:
np.random.randint(0,10)

1

In [24]:
np.random.randint(1,10,5)

array([3, 4, 1, 7, 8])

In [25]:
np.random.randint(1,10,5)

array([5, 8, 6, 3, 2])

In [26]:
np.random.rand(5)

array([0.80458699, 0.58839438, 0.55974414, 0.55442153, 0.50767417])

In [27]:
np.random.randn(10)

array([-3.79346333, -1.46329141,  0.75364314, -1.1698006 , -1.84073721,
        1.64026781,  0.01840803,  0.1734204 ,  0.81784203,  0.37917559])

In [28]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [38]:
newArray = np.random.randint(1,100,10)
newArray

array([13, 66, 21, 85, 96, 25,  4, 62, 89, 27])

In [39]:
newArray.max()

96

In [40]:
newArray.min()


4

In [41]:
newArray.sum() 

488

In [42]:
newArray.mean()

48.8

In [43]:
newArray.argmin()

6

In [44]:
newArray.argmax()

4

In [45]:
detArray =  np.random.randint(1,100,25)
detArray

array([96, 13, 38, 81, 94, 82, 75, 89, 18, 49, 82,  1, 84, 36, 58, 49, 31,
        7, 35,  1, 78, 27, 44, 66, 82])

In [46]:
detArray = detArray.reshape(5,5)
detArray

array([[96, 13, 38, 81, 94],
       [82, 75, 89, 18, 49],
       [82,  1, 84, 36, 58],
       [49, 31,  7, 35,  1],
       [78, 27, 44, 66, 82]])

In [47]:
np.linalg.det(detArray)

182958351.99999997

In [48]:
round(np.linalg.det(detArray))

182958352.0